### PR TITLE
Ticket 6

### PR DESCRIPTION
**Pull request by Kayphaz007**

### CODE REVIEW

**Review by roisinoreilly — CHANGES_REQUESTED** [review]
- Excellent work displaying the comments
- Lovely stuff creating a separate component for the comments; stops the components getting too big and bloated
- Excellent see some loading feedback to let us know something is happening
- Good to see the axios requests extracted into their own file

however there's some changes I'd like you to implement to make it even better:
- an article without comments breaks the page, you'll probably need to go back to your API to figure out why (check where you're rejecting your promise and make sure you have some kind of outer join)
- once you've sorted that, it would be good for the articles which have no comments to get a little messages saying so e.g. 'No comments to show - why not be the first to add one?'
- you're missing the rest of the data from the comments themselves, and it's hard to tell they actually are comments unless you know. Can you include the rest of the data such as the user who posted the comment, votes, and time posted that's available from the api

once you've sorted that send us another PR :)

**Comment by Kayphaz007** [comment]
please how do i know or check that an article without comment breaks my page

**Review by roisinoreilly — CHANGES_REQUESTED** [review]
thanks for making those changes! However you still can't view an article without any comments as you're just getting an error. You can test this yourself on article 37, it's likely to be a problem with your backend that's causing a 404 error, I left comments previous about where the problem will likely be. Once that's sorted send us another PR

**Review by MKD01 — APPROVED** [review]
Great work, im happy for you to merge this in 👍

**Pull request merged**
